-- URJALOOP SUPABASE SCHEMA
-- For Viksit Bharat Hackathon 2047

-- 1. PROFILES (Extends Auth.Users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  phone TEXT UNIQUE,
  location TEXT,
  eco_credits BIGINT DEFAULT 0,
  co2_saved DECIMAL DEFAULT 0,
  waste_processed DECIMAL DEFAULT 0, -- in kg
  role TEXT DEFAULT 'citizen', -- citizen, admin, collector, farmer
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. SMART BINS
CREATE TABLE IF NOT EXISTS public.smart_bins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location_name TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  fill_level INT DEFAULT 0, -- 0 to 100
  status TEXT DEFAULT 'active', -- active, full, maintenance
  last_cleaned TIMESTAMP WITH TIME ZONE,
  type TEXT DEFAULT 'general', -- general, plastic, organic, hazard
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. COMPLAINTS
CREATE TABLE IF NOT EXISTS public.complaints (
  id TEXT PRIMARY KEY, -- CMP-XXX
  user_id UUID REFERENCES auth.users,
  type TEXT NOT NULL,
  location_name TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  severity TEXT DEFAULT 'Medium',
  description TEXT,
  status TEXT DEFAULT 'Submitted', -- Submitted, Under Review, Assigned, In Progress, Resolved
  status_idx INT DEFAULT 0,
  assigned_to TEXT,
  expected_resolution TEXT,
  image_url TEXT,
  ai_validated BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. MARKETPLACE ITEMS
CREATE TABLE IF NOT EXISTS public.marketplace_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price INT NOT NULL, -- in credits
  image TEXT,
  category TEXT, -- Energy, Fertilizer, Raw Material, Biomass
  type TEXT, -- urban, rural
  stock INT DEFAULT 10,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. ACTIVITY LOG (For Dashboard Feed)
CREATE TABLE IF NOT EXISTS public.activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users,
  action TEXT NOT NULL, -- "Scanned Waste", "Earned Credits", "Filed Complaint"
  description TEXT,
  points_earned INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS POLICIES (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_bins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;

-- Public read access for Bins and Marketplace
CREATE POLICY "Public Bins Read" ON public.smart_bins FOR SELECT USING (true);
CREATE POLICY "Public Marketplace Read" ON public.marketplace_items FOR SELECT USING (true);
